# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5a4becce5a4a791dd0f90d81c457731af20850147600507d839a94686bde8b745d24db1d72cc0b1afdac96542dae9989bdc07998e218efeb9e144edbbeb3f0

test:
  secret_key_base: 0fca90097650cd5c7dfdc85f835d0bdc8afcca147c96300aed8e4cf0b52dfd726ae7116500015302a23f68fbcb071fd43e3e3026ab6b9460ab57ad21391b3130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
